Add vector hw
NH5pml30/first-term pull request #2
Opened 2020-06-20 12:37 UTC by NH5pml30

2020-06-20 18:22 UTC, kt-cpp requested changes

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +vector<T>::vector()
default

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +  assert(i < size_);
ассертить "продовый код" можно только в тех местах, где эта гарантия нужна разработчику библиотеки (проверка что его код соблюдает собственные инварианты), а не в тех инвариантах, которые легко может нарушить пользователь библиотеки. Ассерты не контролируются, значит вызов этого метода некорректно будет крашить всю программу -- очень грубое, недопустимое поведение для библиотеки

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +  assert(i < size_);
в коде есть такие же ассерты, нужно разобраться какие действительно нужно убрать, а какие поддерживают инвариант твоего библиотечного кода

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +  size_t before = pos - begin();
ptrdiff_t. В коде еще есть подобные места, нужно чинить.

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +  return;
зачем пустой ретурн в самом конце?

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +void destroy_at(T *data, size_t at)
теперь твои 4 утилитные функции торчат для всех, кто инклюдит твою библиотеку. нужно исправить зону видимости + сделать их статиками.

2020-06-20 18:22 UTC, kt-cpp commented on vector/vector.h
> +    vector swapper(other);
не нужно именованной сущности, сделай vector(other).swap

2020-06-20 19:04 UTC, NH5pml30 commented on vector/vector.h
> +vector<T>::vector()
Сделал default

2020-06-20 19:05 UTC, NH5pml30 commented on vector/vector.h
> +  assert(i < size_);
Убрал все ассерты по контрактам для пользователя

2020-06-20 19:06 UTC, NH5pml30 commented on vector/vector.h
> +  size_t before = pos - begin();
Везде по смыслу нужно расстояние а по контрактам разница > 0, поэтому сделал каст

2020-06-20 19:07 UTC, NH5pml30 commented on vector/vector.h
> +  return;
Убрал

2020-06-20 19:07 UTC, NH5pml30 commented on vector/vector.h
> +void destroy_at(T *data, size_t at)
Сделал их статическими приватными методами

2020-06-20 19:07 UTC, NH5pml30 commented on vector/vector.h
> +    vector swapper(other);
Сделал

2020-06-20 20:06 UTC, kt-cpp approved these changes

2020-06-24 19:04 UTC, merged

2020-06-27 16:13 UTC, NH5pml30 commented
Я случайно перезаписал мастер без вектора(