Bigint
NH5pml30/first-term pull request #3
Opened 2020-06-20 19:27 UTC by NH5pml30

2020-06-20 20:34 UTC, kt-cpp approved these changes
1) copyctor = default. 2) конструктор от инта не учитывает знак аргумента. но с учетом всего кода это мелочи, верю что легко исправить.

2020-06-21 21:06 UTC, kt-cpp commented
sorry man, но нужно переехать на 11 стандарт. для этого нужно избавиться от optional. возможно carry достаточно передавать как place_t ? во всяком случае, можно передать еще бул флаг.
это замечание относится и к бигинт-оптимайзед.

2020-06-22 12:44 UTC, kt-cpp requested changes

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint64_t l64 = (uint64_t{lhs_high & 0x0000FFFF} << 48)| (lhs_low >> 16);
lhs_high & 0x0000FFFF можно сделать отдельной функцией, как low_bytes

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  std::vector<char> reverse;
а почему сразу не std::string?

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        r3_med = k + m - 1 >= rem.data.size() ? 0 : rem.data[k + m - 1],
так писать -- моветон, для каждой переменной с начала строки нужен ее тип

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    using limit = std::numeric_limits<type>;
здесь сразу можно переменную равную limit::max(), попробуй static constexpr

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +       it++, r_it = r_it == r_end ? r_it : std::next(r_it))
так не надо, r_it в тело цикла.

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    left_low = low_bytes(left),
здесь тоже типы с новой строчки

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return (uint64_t{high << 16} << 16) | (low >> 32);
почему бы перед свичем на кастануть high к 64_t и избежать лапши?

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    reverse.push_back((char)((char)rem + '0'));
нужен правильный каст

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    *this += *it - '0';
нужен правильный каст

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.h
> +  void iterate(const std::function<place_t (place_t)> &action);
сделай using на оба вида function

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +             limit::max() - left - carry < right);
если left = limit::max(), carry = 1 не будет плохо? или есть какой-то инвариант перед вызовом функции?

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return std::max(size_t{1}, data.size() - (data.back() == default_place()));
нужен правильный каст була в size_t

2020-06-22 12:44 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                                get_or_default(rhs < 0 ? (int)data.size() : -1));
size в инт плохо... int64_t звучит лучше, но мб ты что-то лучше придумаешь

2020-06-22 12:46 UTC, kt-cpp commented on bigint/big_integer.cpp
> +  return std::max(size_t{1}, data.size() - (data.back() == default_place()));
с булами нужно быть аккуратным. кажется в буле не всегда 0/1, зависит от ABI

2020-06-22 12:55 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +  return std::max(size_t{1}, data.size() - (data.back() == default_place()));
Там будет конвертация типов и [If the source type is bool, the value false is converted to zero and the value true is converted to the value one of the destination type](https://en.cppreference.com/w/cpp/language/implicit_conversion)

2020-06-22 12:55 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +    *this += *it - '0';
Там же полсе промоушна int получается, зачем каст?

2020-06-22 12:57 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +             limit::max() - left - carry < right);
Сумма двух чисел n битности и carry флага всегда влезает в n+1 бит, а если left = max и carry = 1 новый carry = 1 - всё верно.

2020-06-22 13:25 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +    return (uint64_t{high << 16} << 16) | (low >> 32);
Потому что во втором случае от high берутся low_bytes, сейчас поправлю/поправил чтобы понятнее выглядело

2020-06-22 13:33 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +    uint64_t l64 = (uint64_t{lhs_high & 0x0000FFFF} << 48)| (lhs_low >> 16);
Сделал

2020-06-22 13:34 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +  std::vector<char> reverse;
Окей сделал строчку

2020-06-22 13:36 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +        r3_med = k + m - 1 >= rem.data.size() ? 0 : rem.data[k + m - 1],
Написал так

2020-06-22 13:36 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +    using limit = std::numeric_limits<type>;
Сделал

2020-06-22 13:36 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +       it++, r_it = r_it == r_end ? r_it : std::next(r_it))
Сделал

2020-06-22 13:36 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +    left_low = low_bytes(left),
Сделал

2020-06-22 13:37 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +    reverse.push_back((char)((char)rem + '0'));
Сделал

2020-06-22 13:37 UTC, NH5pml30 commented on bigint/big_integer.h
> +  void iterate(const std::function<place_t (place_t)> &action);
Сделал

2020-06-22 13:39 UTC, NH5pml30 commented on bigint/big_integer.cpp
> +                                get_or_default(rhs < 0 ? (int)data.size() : -1));
Сделал int64_t, хотя кажется если в числе 2 млрд 4-байтных цифр там уже другие проблемы будут

2020-06-22 20:29 UTC, merged