Bigint opt
NH5pml30/first-term pull request #4
Opened 2020-06-20 21:49 UTC by NH5pml30

2020-06-21 10:59 UTC, kt-cpp approved these changes

2020-06-21 10:59 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.h
> +    const place_t * begin() const;
обычно делают using iterator = ..., так удобнее пользователю библиотеки

2020-06-21 21:36 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.h
> +    const place_t * begin() const;
Это я поменял, а то комментарий не resolved

2020-06-27 22:03 UTC, kt-cpp requested changes
Уже очень близко к правде. У меня стойкое желание перенести больше логики, связанной с COW в соотв. класс, а не `optimized_buffer`. Надеюсь написал все такие места, где это имеет смысл, но на всякий поищи сам ещё

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +using namespace big_int_util;
Тут нужен не `using`, а погрузить весь код в этот namespace

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  assert(is_dynamic_data() && (new_size > size() || dynamic_data->ref_count > 1));
Кажется этот ассёрт проверяет не совсем то условие, что ты хочешь. Ибо вызываешь ты его при превышении capacity, a не size текущего

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  std::copy_n(static_data, STATIC_BUFFER_SIZE, buffer);
Хоть это не нарушает логику, но почему тут копируется весь старый буффер, а не только `size()` элементов?

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +}
[minor] Кажется стоит к названию это функции добавить `_data`, иначе кажется, что тут забыли размер поменять

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  }
[style] Какой-то странный фрагмент года, первый две ветки сделаны через вложенные `if`, а вторые две через `else if` первого `if` предыдущих двух

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  // only inflate
Почему тут разрешают только расширение? Я вполне могу представить, что в  бигинте может захотеться сужать размер

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  if (dynamic_data->ref_count > 1)
Мб эту повторяющуюся проверку стоит вынести в сам класс `shared_buffer` в виде функции `unique`?

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +}
Эти функции работают менее оптимально чем могли бы для мелкого буффера учитывая, что сейчас его длина легко варьируется

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  new_size = new_size == static_cast<size_t>(-1) ? size() : new_size;
Зачем тут странный каст беззнакового к знаковому?

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  new_size = new_size == static_cast<size_t>(-1) ? size() : new_size;
Ладно это не странный каст, а просто странный код. Лучше избегать таких вот гипноконстант и явно передавать в функцию ожидаемый размер

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  }
В целом я вижу такой паттерн не один раз, я бы вынес эту логику в сам `shared_buffer`, под функцию вида `ensure_unique`, а тут бы писал `dynamic_data = dynamic_data->ensure_unique()`

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.h
> +    static shared_buffer * add_ref(shared_buffer *self)
Почему бы это функции не быть членом класса вместо статической. В отличие от `allocate` тут нет нужны выделять под себя память

2020-06-27 22:03 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  if (dynamic_data->ref_count > 1)
Хотя в конкретном данном случае коммент про `ensure_unique` более актуален. Но `unique` просто пригодится в других местах

2020-06-28 11:52 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +using namespace big_int_util;
Это поправил

2020-06-28 11:53 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  assert(is_dynamic_data() && (new_size > size() || dynamic_data->ref_count > 1));
Вообще это условие было на то что хоть что-то меняется, но так лучше, поправил

2020-06-28 11:54 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  std::copy_n(static_data, STATIC_BUFFER_SIZE, buffer);
Поправил

2020-06-28 11:54 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +}
Сделал

2020-06-28 11:55 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  }
поправил

2020-06-28 11:57 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  // only inflate
У меня увеличивается в арифметических операциях чтобы добить до одинакового размера, а удаляется pop_back() по одному разряду, поэтому такое не надо. Вообще там ничего особо не меняется, поправил

2020-06-28 12:02 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  if (dynamic_data->ref_count > 1)
Проверку вынес в функцию shared_buffer'а

2020-06-28 12:03 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +}
Ничего не понял, почему медленнее? Происходит вызов resize, в котором определяется, что буфер статический и то что новый размер меньше его полного размера, например, и происходит std::fill на 1 элемент. Как можно сделать быстрее?

2020-06-28 12:04 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  new_size = new_size == static_cast<size_t>(-1) ? size() : new_size;
Сделал ещё одну функцию без аргументов

2020-06-28 12:09 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  }
Если честно я не понимаю как это всё нормально выносить в shared_buffer. Чтобы не хранить размер дважды, shared_buffer получается более низкоуровневый (в смысле того что он работает только с capacity, а операции копирования из старого буфера, заполнение дефолтными значениями до размера и тд используют size буфера, а не capacity). Всё равно не так много действий выносятся, а например заполнять dynamic_data флажок и менять размер и так надо в optimized_buffer'е.

2020-06-28 12:10 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.h
> +    static shared_buffer * add_ref(shared_buffer *self)
Вообще писал так чтобы всё одинаково было. Сделал так

2020-06-28 12:50 UTC, NH5pml30 commented on bigint-optimized/optimized_buffer.cpp
> +  }
upd: тупо вынес эти методы в shared_buffer
Мне кажется это выглядит достаточно убого, но хз

2020-06-29 22:26 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +}
Соре мой косяк. Проглядел. Действительно всё норм

2020-06-30 12:12 UTC, kt-cpp commented on bigint-optimized/optimized_buffer.cpp
> +  }
Это логичное разделение логики. С ростом кода без такого подхода  становится оч больно

2020-06-30 12:19 UTC, kt-cpp approved these changes
Опять экономишь на фигурных скобках)))
Но принимается и так

2020-06-30 12:20 UTC, merged